trigger:
  branches:
    include:
      - '*'
    exclude:
      - refs/pull/*/head
  paths:
    exclude:
      - docs/*
      - .github/*

variables:
  buildConfiguration: Debug
  dotnetCoreSdkVersion: 3.1.107
  dotnetCoreSdk5Version: 5.0.100
  ddApiKey: $(DD_API_KEY)
  DD_DOTNET_TRACER_MSBUILD:

# Declare the datadog agent as a resource to be used as a pipeline service
resources:
  containers:
  - container: dd_agent
    image: datadog/agent
    ports:
    - 8126:8126
    env:
      DD_API_KEY: $(ddApiKey)
      DD_INSIDE_CI: true

jobs:

- job: managed
  strategy:
    matrix:
      windows:
        imageName: windows-2019
      linux:
        imageName: ubuntu-18.04
  pool:
    vmImage: $(imageName)

  # Enable the Datadog Agent service for this job
  services:
    dd_agent: dd_agent

  steps:

  # Install the tracer latest stable release to attach the profiler to the build and test steps.
  # The script exposes the required environment variables to the following steps
  - task: PowerShell@2
    displayName: Install profiler latest release
    inputs:
      filePath: ./.azure-pipelines/setup_tracer.ps1

  - task: UseDotNet@2
    displayName: install dotnet core runtime 2.1
    inputs:
      packageType: runtime
      version: 2.1.x

  - task: UseDotNet@2
    displayName: install dotnet core runtime 3.0
    inputs:
      packageType: runtime
      version: 3.0.x

  - task: UseDotNet@2
    displayName: install dotnet core sdk 3.1
    inputs:
      packageType: sdk
      version: $(dotnetCoreSdkVersion)

  - task: UseDotNet@2
    displayName: install dotnet core sdk 5.0
    inputs:
      packageType: sdk
      version: $(dotnetCoreSdk5Version)

  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: build
      configuration: $(buildConfiguration)
      arguments: -l:DatadogLogger,"$(DD_DOTNET_TRACER_MSBUILD)"
      projects: |
        src/**/*.csproj
        test/**/*.Tests.csproj
        benchmarks/**/*.csproj
        !src/Datadog.Trace.Tools.Runner/*.csproj
    env:
      DD_SERVICE_NAME: dd-tracer-dotnet

  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: test
      configuration: $(buildConfiguration)
      projects: test/**/*.Tests.csproj
    env:
      DD_SERVICE_NAME: dd-tracer-dotnet

- job: windows_profiler
  strategy:
    matrix:
      x64:
        buildPlatform: x64
      x86:
        buildPlatform: x86
  pool:
    vmImage: windows-2019

  steps:

  - task: UseDotNet@2
    displayName: install dotnet core sdk 3.1
    inputs:
      packageType: sdk
      version: $(dotnetCoreSdkVersion)

  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: build
      configuration: $(buildConfiguration)
      projects: |
        src/Datadog.Trace.ClrProfiler.Managed.Loader/Datadog.Trace.ClrProfiler.Managed.Loader.csproj
        sample-libs/**/Samples.ExampleLibrary*.csproj

  - task: NuGetToolInstaller@1
    displayName: install nuget

  - task: NuGetCommand@2
    displayName: nuget restore
    inputs:
      restoreSolution: Datadog.Trace.Native.sln
      verbosityRestore: Normal

  - task: MSBuild@1
    displayName: msbuild
    inputs:
      solution: Datadog.Trace.proj
      platform: $(buildPlatform)
      configuration: $(buildConfiguration)
      msbuildArguments: /t:BuildCpp;BuildCppTests
      maximumCpuCount: true

  - script: Datadog.Trace.ClrProfiler.Native.Tests.exe --gtest_output=xml
    displayName: run tests
    workingDirectory: $(System.DefaultWorkingDirectory)/test/Datadog.Trace.ClrProfiler.Native.Tests/bin/$(buildConfiguration)/$(buildPlatform)

  - task: PublishTestResults@2
    displayName: publish test results
    inputs:
      testResultsFiles: test/**/test*.xml
      buildPlatform: $(buildPlatform)
      buildConfiguration: $(buildConfiguration)
    condition: succeededOrFailed()

- job: macos_profiler
  pool:
    vmImage: macOS-10.15
  steps:

  - task: UseDotNet@2
    displayName: install dotnet core sdk 3.1
    inputs:
      packageType: sdk
      version: $(dotnetCoreSdkVersion)

  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: build
      configuration: $(buildConfiguration)
      projects: |
        src/Datadog.Trace.ClrProfiler.Managed.Loader/Datadog.Trace.ClrProfiler.Managed.Loader.csproj
  
  - script: |
      mkdir -p /opt
      sudo chmod -R 777 /opt
      cd /opt && git clone --depth 1 --branch v3.3.0 https://github.com/nlohmann/json.git
      cd /opt && git clone --depth 1 --branch 2018-10-01 https://github.com/google/re2.git
      cd /opt/re2 && env CXXFLAGS="-O3 -g -fPIC" make 
      cd /opt && git clone --depth 1 --branch 5.3.0 https://github.com/fmtlib/fmt.git
      cd /opt/fmt && cmake -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE . && make
    displayName: build_dependencies

  - script: |
      cd ./src/Datadog.Trace.ClrProfiler.Native
      mkdir -p ./obj/Debug/x64
      cd ./obj/Debug/x64
      cmake ../../.. -DOSX=1
      make
    displayName: build_profiler


- job: linux_profiler
  pool:
    vmImage: ubuntu-18.04
  steps:

  - task: UseDotNet@2
    displayName: install dotnet core sdk 3.1
    inputs:
      packageType: sdk
      version: $(dotnetCoreSdkVersion)

  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: build
      configuration: $(buildConfiguration)
      projects: |
        src/Datadog.Trace.ClrProfiler.Managed.Loader/Datadog.Trace.ClrProfiler.Managed.Loader.csproj
  
  - script: |
      echo "deb http://llvm.org/apt/bionic/ llvm-toolchain-bionic-3.9 main" | sudo tee /etc/apt/sources.list.d/llvm.list
      wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
      sudo apt-get update
      sudo apt-get install -y llvm-3.9 clang-3.9
      sudo cd /usr/lib/llvm-3.9/lib && ln -s ../../x86_64-linux-gnu/liblldb-3.9.so.1 liblldb-3.9.so.1
      mkdir -p /opt
      sudo chmod -R 777 /opt
      cd /opt && git clone --depth 1 --branch v3.3.0 https://github.com/nlohmann/json.git
      cd /opt && git clone --depth 1 --branch 2018-10-01 https://github.com/google/re2.git
      cd /opt/re2 && env CXXFLAGS="-O3 -g -fPIC" make 
      cd /opt && git clone --depth 1 --branch 5.3.0 https://github.com/fmtlib/fmt.git
      cd /opt/fmt && cmake -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE . && make
    displayName: build_dependencies

  - script: |
      cd ./src/Datadog.Trace.ClrProfiler.Native
      mkdir -p ./obj/Debug/x64
      cd ./obj/Debug/x64
      CXX=clang++-3.9 CC=clang-3.9 cmake ../../..
      make
    displayName: build_profiler