name: Auto trigger AAS version bump

on:
  release:
    types: [published]

jobs:
  trigger_aas_release:
    runs-on: ubuntu-latest

    steps:        
      - name: Trigger AAS release
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN_PIERO }}" \
          https://api.github.com/repos/pierotibou/datadog-aas-extension/dispatches \
          -d '{"event_type": "dd-trace-dotnet-release", "client_payload": {"is_prerelease":"${{github.event.release.prerelease}}", "version":"${{github.event.release.tag_name}}" } }'