name: Create hotfix branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Hotfix Version Number (x.x.x)'
        required: true
      is_prerelease:
        description: 'Is Prerelease version? (true/false)'
        default: 'false'
        required: true

jobs:
  bump_version:
    runs-on: windows-latest
    permissions:
      contents: write # Push branches
      issues: write # change milestones 
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      NewVersion: "${{ github.event.inputs.version }}"
      NewIsPrerelease: "${{ github.event.inputs.is_prerelease }}"

    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: "Configure Git Credentials"
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0
        with:
          global-json-file: global.json

      - name: "Bump Version"
        run: .\tracer\build.ps1 UpdateVersion

      - name: "Verify Changes"
        id: changes
        run: .\tracer\build.ps1 VerifyChangedFilesFromVersionBump -ExpectChangelogUpdate false

      - name: "Output Version"
        id: versions
        run: .\tracer\build.ps1 OutputCurrentVersionToGitHub

      - name: "Push hotfix branch"
        run: |
          git checkout -b hotfix/${{ steps.versions.outputs.full_version }}
          git add .
          git commit -m "[Version Bump] ${{steps.versions.outputs.full_version}}"
          git push origin -u hotfix/${{ steps.versions.outputs.full_version }}
