# Based on https://app.datadoghq.com/ci/setup/static-analysis?provider=github
on: [push]

jobs:
  check-quality:
    if: github.actor != 'dependabot[bot]'  # secrets are not available to dependabot
    runs-on: ubuntu-latest
    name: Datadog Static Analyzer
    permissions:
      actions: read # read secrets
      contents: read
      statuses: write # add status checks (?)
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Check code meets quality standards
        id: datadog-static-analysis
        uses: DataDog/datadog-static-analyzer-github-action@8340f18875fcefca86844b5f947ce2431387e552 # v3.0.0
        with:
          dd_api_key: ${{ secrets.DD_API_KEY }}
          dd_app_key: ${{ secrets.DD_APP_KEY }}
          dd_site: datadoghq.com
          cpu_count: 2

