name: Force manual version bump

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Next Version Number (x.y.z). On master, other workflows expect only versions of the form x.y.0. Consider using the "create hotfix branch" workflow for patch version bumps.'
        required: true
      is_prerelease:
        description: "Is Prerelease version? (true/false)"
        default: "false"
        required: true

jobs:
  bump_version:
    runs-on: windows-latest
    permissions:
      issues: write # Closes milestones
      id-token: write # Required for dd-octo-sts authentication
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      NewVersion: "${{ github.event.inputs.version }}"
      NewIsPrerelease: "${{ github.event.inputs.is_prerelease }}"

    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true

      - name: Get dd-octo-sts token
        uses: DataDog/dd-octo-sts-action@acaa02eee7e3bb0839e4272dacb37b8f3b58ba80 # v1.0.3
        id: octo-sts
        with:
          scope: DataDog/dd-trace-dotnet
          policy: self.force_manual_version_bump.create-pr

      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - uses: actions/setup-dotnet@2016bd2012dba4e32de620c46fe006a3ac9f0602 # v5.0.1
        with:
          global-json-file: global.json

      - name: "Bump Version"
        run: .\tracer\build.ps1 UpdateVersion

      - name: "Verify Changes"
        id: changes
        run: .\tracer\build.ps1 VerifyChangedFilesFromVersionBump -ExpectChangelogUpdate false

      - name: "Output Version"
        id: versions
        run: .\tracer\build.ps1 OutputCurrentVersionToGitHub

      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
        with:
          token: ${{ steps.octo-sts.outputs.token }}
          branch: "version-bump-${{steps.versions.outputs.full_version}}"
          commit-message: "[Version Bump] ${{steps.versions.outputs.full_version}}"
          delete-branch: true
          title: "[Version Bump] ${{steps.versions.outputs.full_version}}"
          reviewers: "DataDog/apm-dotnet"
          body: "${{steps.changes.outputs.release_notes}}"

      - name: Display output
        run: |
          echo "Pull Request Number - ${{ steps.pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.pr.outputs.pull-request-url }}"
