name: Generate package versions and push

on:
  workflow_dispatch:

jobs:
  generate_package_versions:
    runs-on: windows-latest
    permissions:
      contents: write # Pushes to a branch
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    steps:
      - name: Fail if branch is on master
        if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/master'
        run: |
          echo "This workflow should not be triggered with workflow_dispatch on the master branch"
          exit 1

      - name: Support longpaths
        run: git config --system core.longpaths true

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5.1.0
        with:
          global-json-file: global.json

      - name: "Regenerating package versions"
        run: .\tracer\build.ps1 GeneratePackageVersions

      - name: Create commits
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "Updated package versions"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
