name: Verify integrations map correctly added

on:
  pull_request:
  workflow_dispatch:

jobs:
  bump_package_versions:
    runs-on: windows-latest
    timeout-minutes: 96 # max + 3*std over the last 3700 runs
    permissions:
      contents: read

    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true

      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - uses: actions/setup-dotnet@2016bd2012dba4e32de620c46fe006a3ac9f0602 # v5.0.1
        with:
          global-json-file: global.json

      - name: "Regenerating package versions"
        run: .\tracer\build.ps1 GeneratePackageVersions

      - name: Report error
        if: failure()
        run: |
          echo "## :warning: Error generating package versions" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "New integration detected. You must update the [IntegrationGroup.IntegrationMap](tracer/build/_build/Honeypot/IntegrationGroups.cs)" >> $GITHUB_STEP_SUMMARY
          echo "class to include the new integration." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "If your new integration uses multi-api testing to test multiple package versions," >> $GITHUB_STEP_SUMMARY
          echo "list the NuGet package in the associated array. Otherwise use an empty array." >> $GITHUB_STEP_SUMMARY

